nicer output.

diff --git a/setup211 b/setup211
--- a/setup211
+++ b/setup211
@@ -1,13 +1,14 @@
 #!/bin/sh
 
-srcdir=/home/jesse/pub/etc
-dstdir=$HOME
+set -e
+
+srcdir=/home/jesse/pub/etc/
+dstdir=${HOME%/}/
+prog=${0##*/}
 
 if [ -n "$1" ]; then
-    dstdir=$1
+    dstdir=${1%/}/
 fi
-
-prog=${0##*/}
 
 backup_file () {
     local dst=$1
@@ -32,25 +33,31 @@ backup_file () {
 
     backup_file "$bak"
     mv "$dst" "$bak"
-    echo "$prog: Saved $descr ${dst##*/} as ${bak##*/}"
+    echo " • Saved $descr ${dst##*/} as ${bak##*/}"
 }
 
 replace_file () {
-    local src=$srcdir/$1
-    local dst=$dstdir/.$1
+    local src=${srcdir}$1
+    local dst=${dstdir}.$1
 
     if ! [ -f "$src" ]; then
         exec >&2
-        echo "$prog: Error: Could not install ${dst##*/}"
+        echo "$prog: error: Could not install ${dst##*/}"
         echo "This is quite surprising. Please report a bug."
         exit 1
     fi
 
+    if diff "$src" "$dst" >/dev/null 2>&1; then
+        echo >&2 "$prog: warning: You already have my ${dst##*/}; skipping..."
+        return 0
+    fi
+
     backup_file "$dst"
     cp "$src" "$dst"
-    echo >&2 "$prog: Installed CS 211’s ${dst##*/} to $dstdir"
+    echo " • Installed ${dst##*/} to $dstdir"
 }
 
+echo "Installing CS 211’s default dotfiles to $dstdir..."
 replace_file tcshrc
 replace_file emacs
-
+echo "Installation complete."
